### PR TITLE
feat: Add logo for certificate

### PR DESCRIPTION
**Pull request by PeterMerkert**

### CODE REVIEW

**Comment by bangretraced** [comment]
as you are allowed null file here, so will also nullable in db?

**Comment by bangretraced** [comment]
ah i guess you create new certificates_logo table?

**Comment by PeterMerkert** [comment]
> ah i guess you create new certificates_logo table?

No, we just need one logo file. Will be added directly to the `certificates` table. :-) So, no array, but just one file.

**Comment by PeterMerkert** [comment]
> as you are allowing null file here, so will also nullable in db?

I liked your idea: We allow everything to be nullable till you request review. During that execution, we cross check if all values which are required are available. 
Instead of pictures, we now check that there is a logo attached.

**Pull request merged**
