### PR TITLE
feat: Add link ID when creating supply chain and graph serialization

### PR DESCRIPTION
**Pull request by PeterMerkert**

### CODE REVIEW

**Comment by PeterMerkert** [comment]
I will leave open till I fixed API and then merge or update change

**Comment by bangretraced** [comment]
did you remove param `deep` from products/get ?
```
module.exports.get = {
	type: 'object',
	properties: {
		supplyChain: {type: 'boolean', default: false},
		attributes: {type: 'boolean', default: false},
		variations: {type: 'boolean', default: false},
		orders: {type: 'boolean', default: false}
	}
}
```

**Comment by bangretraced** [comment]
and no more categories in materials, right?
```
properties: {
			title: {type: 'string', minLength: 1},
			description: {type: 'string', minLength: 1},
			externalLink: {anyOf: [{type: 'string', format: 'uri', minLength: 1}, {type: 'null'}]},
			pictures: file.list
		}
```

**Comment by PeterMerkert** [comment]
> did you remove param deep from products/get ?
Yes

> and no more categories in materials, right?
Yes

**Pull request merged**
