### PR TITLE
feat: Allow account creation simply with name of user

### PR DESCRIPTION
**Pull request by PeterMerkert**
ONLY MERGE BY PETER

### CODE REVIEW

**Comment by bangretraced** [comment]
who will create this user? I guess admin?

**Comment by PeterMerkert** [comment]
We need to adjust the schemas for open consumer/user signups. New accounts won't be created by admins, but we will move towards an open sign up, where everyone can simply sign up.

**Comment by bangretraced** [comment]
ah so I guess we need to add more role to the USER_ROLES_ENUM which is including something like `USER`

**Comment by PeterMerkert** [comment]
We have already `CONSUMER` :)

**Pull request merged**
